### ISSUE TITLE
exclude plotly plots from slides generator 

### ISSUE THREAD

**Issue by hadrilec** [pyr-opendatafr/graffiti#9]

**Comment by jdesclodure** [comment]
I think this [commit](https://github.com/pyr-opendatafr/graffiti/commit/a72373099bb0d462a506ea86eeda7ec7b2e1b72a) should be enough to exclude plotly plots from the slider generator.

**Comment by jdesclodure** [comment]
After plotting a non interactive and then an interactive plot, the name of non interactive is still available in the choices for the slides. So I added an else condition in this [commit](https://github.com/pyr-opendatafr/graffiti/commit/8c3a23c37cd90260d73be19d6382fad25ec35cea) to forget the previous plot name. Maybe you'll find a cleaner fix.

**Comment by hadrilec** [comment]
Thanks Julien, I think this is enough to close the issue.
